#ifndef __KSU_DYNSYM_LIST_H
#define __KSU_DYNSYM_LIST_H

#include <linux/version.h>

/* every symbol the module would otherwise take from the loader
 * functions get a trampoline and one lookup pass after discovery
 * export status does not matter */
#define KSU_DYNSYM_LIST(X)				\
	X(abort_creds)					\
	X(alloc_anon_inode)				\
	X(alloc_file_pseudo)				\
	X(__alloc_pages)				\
	X(__alloc_pages_nodemask)			\
	X(__alloc_pages_noprof)				\
	X(alloc_uid)					\
	X(anon_inode_create_getfile)			\
	X(anon_inode_getfile)				\
	X(anon_inode_getfile_secure)			\
	X(__arch_copy_from_user)			\
	X(__arch_copy_to_user)				\
	X(avc_has_perm)					\
	X(avc_ss_reset)					\
	X(avtab_alloc)					\
	X(avtab_destroy)				\
	X(avtab_insert_nonunique)			\
	X(avtab_search_node)				\
	X(avtab_search_node_next)			\
	X(bcmp)						\
	X(bin2hex)					\
	X(caches_clean_inval_pou)			\
	X(call_rcu)					\
	X(__cfi_slowpath)				\
	X(__cfi_slowpath_diag)				\
	X(change_pid)					\
	X(__check_object_size)				\
	X(commit_creds)					\
	X(cond_compute_av)				\
	X(copy_from_user_nofault)			\
	X(__copy_overflow)				\
	X(_copy_to_iter)				\
	X(copy_to_kernel_nofault)			\
	X(copy_to_user_nofault)				\
	X(crypto_alloc_shash)				\
	X(crypto_destroy_tfm)				\
	X(crypto_shash_digest)				\
	X(dcache_clean_inval_poc)			\
	X(dentry_open)					\
	X(dentry_open_nonotify)				\
	X(down_read)					\
	X(down_write)					\
	X(d_path)					\
	X(ebitmap_cmp)					\
	X(ebitmap_contains)				\
	X(ebitmap_destroy)				\
	X(ebitmap_equal)				\
	X(ebitmap_get_bit)				\
	X(ebitmap_set_bit)				\
	X(ext4_unregister_sysfs)			\
	X(fd_install)					\
	X(fget)						\
	X(filp_close)					\
	X(filp_open)					\
	X(_find_first_bit)				\
	X(_find_next_bit)				\
	X(find_pid_ns)					\
	X(find_task_by_vpid)				\
	X(find_vpid)					\
	X(finish_wait)					\
	X(__flush_dcache_area)				\
	X(__flush_icache_range)				\
	X(fput)						\
	X(__free_pages)					\
	X(free_pids)					\
	X(free_uid)					\
	X(fsnotify_add_mark)				\
	X(fsnotify_alloc_group)				\
	X(fsnotify_destroy_mark)			\
	X(fsnotify_init_mark)				\
	X(fsnotify_put_group)				\
	X(fsnotify_put_mark)				\
	X(generic_file_llseek)				\
	X(get_pid_task)					\
	X(__get_task_comm)				\
	X(get_task_cred)				\
	X(get_unused_fd_flags)				\
	X(groups_alloc)					\
	X(groups_free)					\
	X(groups_sort)					\
	X(__hashtab_insert)				\
	X(ihold)					\
	X(init_wait_entry)				\
	X(__init_waitqueue_head)			\
	X(iput)						\
	X(iterate_dir)					\
	X(kernel_read)					\
	X(kernel_write)					\
	X(kern_path)					\
	X(kfree)					\
	X(__kmalloc)					\
	X(__kmalloc_cache_noprof)			\
	X(__kmalloc_noprof)				\
	X(kmalloc_trace)				\
	X(kmem_cache_alloc_trace)			\
	X(kmemdup)					\
	X(kmemdup_noprof)				\
	X(kmemdup_nul)					\
	X(kobject_del)					\
	X(krealloc)					\
	X(krealloc_node_align_noprof)			\
	X(krealloc_noprof)				\
	X(kstrdup)					\
	X(kstrtouint)					\
	X(ksys_unshare)					\
	X(ktime_get)					\
	X(kvfree)					\
	X(kvfree_call_rcu)				\
	X(kvmalloc_node)				\
	X(__kvmalloc_node_noprof)			\
	X(kvrealloc)					\
	X(kvrealloc_node_align_noprof)			\
	X(kvrealloc_noprof)				\
	X(__list_add_valid)				\
	X(__list_add_valid_or_report)			\
	X(__list_del_entry_valid)			\
	X(__list_del_entry_valid_or_report)		\
	X(memchr)					\
	X(memcpy)					\
	X(mls_compute_context_len)			\
	X(mls_context_to_sid)				\
	X(mls_sid_to_context)				\
	X(module_put)					\
	X(__mutex_init)					\
	X(mutex_lock_interruptible)			\
	X(noop_llseek)					\
	X(ns_get_path)					\
	X(override_creds)				\
	X(path_get)					\
	X(path_mount)					\
	X(path_put)					\
	X(path_umount)					\
	X(policydb_context_isvalid)			\
	X(policydb_destroy)				\
	X(policydb_filenametr_search)			\
	X(policydb_load_isids)				\
	X(policydb_read)				\
	X(policydb_write)				\
	X(prepare_creds)				\
	X(prepare_to_wait_event)			\
	X(__put_cred)					\
	X(__put_task_struct)				\
	X(__put_task_struct_rcu_cb)			\
	X(put_unused_fd)				\
	X(queue_work_on)				\
	X(___ratelimit)					\
	X(_raw_read_lock)				\
	X(_raw_read_unlock)				\
	X(_raw_spin_lock)				\
	X(_raw_spin_lock_irq)				\
	X(_raw_spin_lock_irqsave)			\
	X(_raw_spin_unlock)				\
	X(_raw_spin_unlock_irq)				\
	X(_raw_spin_unlock_irqrestore)			\
	X(_raw_write_lock_irq)				\
	X(_raw_write_unlock_irq)			\
	X(__rcu_read_lock)				\
	X(__rcu_read_unlock)				\
	X(refcount_warn_saturate)			\
	X(register_kprobe)				\
	X(register_kretprobe)				\
	X(revert_creds)					\
	X(schedule)					\
	X(scnprintf)					\
	X(seccomp_filter_release)			\
	X(security_compute_av_user)			\
	X(security_context_str_to_sid)			\
	X(security_context_to_sid)			\
	X(security_cred_getsecid)			\
	X(security_inode_init_security_anon)		\
	X(security_release_secctx)			\
	X(security_secctx_to_secid)			\
	X(security_secid_to_secctx)			\
	X(security_sid_to_context)			\
	X(selinux_status_update_policyload)		\
	X(selnl_notify_policyload)			\
	X(set_cred_ucounts)				\
	X(__set_fixmap)					\
	X(set_fs_pwd)					\
	X(set_groups)					\
	X(sidtab_context_to_sid)			\
	X(sidtab_destroy)				\
	X(sidtab_search_entry)				\
	X(sidtab_sid2str_get)				\
	X(sidtab_sid2str_put)				\
	X(sized_strscpy)				\
	X(snprintf)					\
	X(sprintf)					\
	X(sscanf)					\
	X(static_key_count)				\
	X(static_key_disable)				\
	X(static_key_enable)				\
	X(stop_machine)					\
	X(strcpy)					\
	X(strncpy_from_user)				\
	X(strncpy_from_user_nofault)			\
	X(strscpy)					\
	X(strscpy_pad)					\
	X(strsep)					\
	X(symtab_insert)				\
	X(symtab_search)				\
	X(synchronize_rcu)				\
	X(synchronize_srcu)				\
	X(__task_pid_nr_ns)				\
	X(task_work_add)				\
	X(tracepoint_probe_register_prio)		\
	X(tracepoint_probe_unregister)			\
	X(try_module_get)				\
	X(unregister_kprobe)				\
	X(unregister_kretprobe)				\
	X(up_read)					\
	X(up_write)					\
	X(vmalloc)					\
	X(vmalloc_noprof)				\
	X(__wake_up)					\
	X(__warn_printk)

/* validate_usercopy_range became a static key in 6.18 and is defined
 * in dynsym_data.c there instead of a shim */
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 18, 0)
#define KSU_DYNSYM_LEGACY(X)
#else
#define KSU_DYNSYM_LEGACY(X) X(validate_usercopy_range)
#endif

#endif
